annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 1.0.0
name: cbom-repository
description: A Helm chart for CBOM Repository.
home: https://github.com/OmniTrustILM/cbom-repository
icon: https://github.com/OmniTrustILM.png
dependencies:
  - name: czertainly-lib
    repository: oci://harbor.3key.company/czertainly-helm
    # repository: file://../czertainly-lib
    version: 1.4.2
keywords:
  - omnitrust
  - trust
  - management
  - lifecycle
  - platform
  - cbom
  - repository
maintainers:
  - name: OmniTrustILM
    email: info@omnitrust.com
    url: https://github.com/OmniTrustILM
type: application
sources:
  - https://github.com/OmniTrustILM/cbom-repository
  - https://www.omnitrust.com
  - https://docs.omnitrust.com
version: 1.1.0-develop
