annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 1.1.0
name: cbom-repository
description: A Helm chart for CBOM Repository.
home: https://github.com/OmniTrustILM/cbom-repository
icon: https://github.com/OmniTrustILM.png
dependencies:
  - name: ilm-lib
    repository: oci://hub.omnitrustregistry.com/ilm-helm
    # repository: file://../ilm-lib
    version: 1.4.2-1
keywords:
  - ilm
  - trust
  - management
  - lifecycle
  - platform
  - cbom
  - repository
maintainers:
  - name: OmniTrustILM
    email: ilm@omnitrust.com
    url: https://github.com/OmniTrustILM
type: application
sources:
  - https://github.com/OmniTrustILM/cbom-repository
  - https://www.omnitrust.com
  - https://docs.otilm.com
version: 1.1.0
