sonar.projectKey=ilm_cbom-repository
sonar.organization=ilm

sonar.go.coverage.reportPaths=coverage.out
sonar.go.golangci-lint.reportPaths=golangci-lint-report.xml

sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=**/*_test.go,cmd/cbom-repository/main.go
